name: EssentialsPM
version: 1.0.0-Beta1
api: 4.0.0
main: Drama_Lvl1\EssentialsPM\EssentialsPM
author: Drama_Lvl1
description: This is a Essentials Plugin for PocketMine-MP

permissions:
  essentialspm.command.tell:
    default: true
    description: send a message directly to a player
    
  essentialspm.command.reply:
    default: true
    description: replies to the last person you write with
    
  essentialspm.command.msgtoggle:
    default: true
    description: blocks direct messages to you
